export class StudentColumns {

    static columns: any;

    static generateColumns(): any {
        return [
            {
                prop: 'name',
                name: 'Név',
                width: 150,
                sortable: true,
                draggable: true,
                resizeable: true,
                canAutoResize: false,
                visible: true,
            },
            {
                prop: 'email',
                name: 'Email',
                headerName: 'Email',
                width: 150,
                sortable: true,
                draggable: true,
                resizeable: true,
                canAutoResize: false,
                visible: true,
            },
            {
                prop: 'levelOne',
                name: '1-es',
                width: 100,
                sortable: true,
                draggable: true,
                resizeable: true,
                canAutoResize: false,
                visible: true,
            },
            {
                prop: 'levelTwo',
                name: '2-es',
                width: 100,
                sortable: true,
                draggable: true,
                resizeable: true,
                canAutoResize: false,
                visible: true,
            },
            {
                prop: 'levelThree',
                name: '3-as',
                width: 100,
                sortable: true,
                draggable: true,
                resizeable: true,
                canAutoResize: false,
                visible: true,
            },
            {
                prop: 'levelThreeC',
                name: '3/C',
                width: 100,
                sortable: true,
                draggable: true,
                resizeable: true,
                canAutoResize: false,
                visible: true,
            },
            {
                prop: 'levelFourA',
                name: '4A',
                width: 100,
                sortable: true,
                draggable: true,
                resizeable: true,
                canAutoResize: false,
                visible: true,
            },
            {
                prop: 'levelFourB',
                name: '4B',
                width: 100,
                sortable: true,
                draggable: true,
                resizeable: true,
                canAutoResize: false,
                visible: true,
            },
            {
                prop: 'levelFourB2',
                name: '4B/2',
                width: 100,
                sortable: true,
                draggable: true,
                resizeable: true,
                canAutoResize: false,
                visible: true,
            },
            {
                prop: 'levelFive',
                name: '5-ös',
                width: 100,
                sortable: true,
                draggable: true,
                resizeable: true,
                canAutoResize: false,
                visible: true,
            },
            {
                prop: 'levelSix',
                name: '6-os',
                width: 100,
                sortable: true,
                draggable: true,
                resizeable: true,
                canAutoResize: false,
                visible: true,
            },
            {
                prop: 'levelSeven',
                name: '7-es',
                width: 100,
                sortable: true,
                draggable: true,
                resizeable: true,
                canAutoResize: false,
                visible: true,
            },
            {
                prop: 'levelEight1',
                name: '8/1-es',
                width: 100,
                sortable: true,
                draggable: true,
                resizeable: true,
                canAutoResize: false,
                visible: true,
            },
            {
                prop: 'uti1',
                name: 'Uti 1',
                width: 100,
                sortable: true,
                draggable: true,
                resizeable: true,
                canAutoResize: false,
                visible: true,
            },
            {
                prop: 'uti2',
                name: 'Uti 2',
                width: 100,
                sortable: true,
                draggable: true,
                resizeable: true,
                canAutoResize: false,
                visible: true,
            },
            {
                prop: 'uti3',
                name: 'Uti 3',
                width: 100,
                sortable: true,
                draggable: true,
                resizeable: true,
                canAutoResize: false,
                visible: true,
            },
            {
                prop: 'uti3plus',
                name: 'Uti 3+',
                width: 100,
                sortable: true,
                draggable: true,
                resizeable: true,
                canAutoResize: false,
                visible: true,
            },
            {
                prop: 'uti4',
                name: 'Uti 4',
                width: 100,
                sortable: true,
                draggable: true,
                resizeable: true,
                canAutoResize: false,
                visible: true,
            },
            {
                prop: 'tk1',
                name: 'TK 1',
                width: 100,
                sortable: true,
                draggable: true,
                resizeable: true,
                canAutoResize: false,
                visible: true,
            },
            {
                prop: 'tk2',
                name: 'TK 2',
                width: 100,
                sortable: true,
                draggable: true,
                resizeable: true,
                canAutoResize: false,
                visible: true,
            },
            {
                prop: 'tk3',
                name: 'TK 3',
                width: 100,
                sortable: true,
                draggable: true,
                resizeable: true,
                canAutoResize: false,
                visible: true,
            },
            {
                prop: 'tk4',
                name: 'TK 4',
                width: 100,
                sortable: true,
                draggable: true,
                resizeable: true,
                canAutoResize: false,
                visible: true,
            },
        ];
    }
}
